#####
# collectionbuilder-gh
# a Jekyll Digital Collection Generator
# designed for GitHub Pages
#####

# URL variables
# url is your gh-pages base, following the pattern: username.github.io
url: https://ncflib.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /BodiesMinds-Group3
# location of code, the full url to your github repository
source-code: https://github.com/ncflib

# Site settings
# title of site appears in banner
title: Pain and Performance
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Viewing of the "Overly-Abled"
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The collection featured on this site is organized around core themes of pain and performance, as they are deployed across four categories common to circus “freak shows”: swords and sword swallowing, needles and nails, extreme strength, and performers inflicting pain on another. In each case, the performers’ ability to complete these feats inspires an awe that may override sympathy. The viewer’s initial wince is assuaged by the performers’ stoic expressions or winning smiles, betraying no trace of pain. Otherwise, their faces are obscured, or their bodies are upstaged by elaborate sets and costumes. Their incredible strength or their tolerance for pain renders them superhuman, and thus other than human. While circus freak shows often featured performers and bodies that were visibly physically disabled, we call the subjects of this collection “overly-abled,” in order to highlight their difference but still call attention to the similar ways in which they are dehumanized."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Bodies and Minds Group 3
# collection project date, when did you publish this
collection-date: "2020"

# Collection settings
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: collection-metadata 

# google services [optional!]
# leave these blank or comment out to NOT include google code
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# Robots exclude
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)

# build settings
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
